spring:
  application:
    name: agendafacil-api

  datasource:
    url: jdbc:mysql://localhost:3306/agendafacil
    username: root
    password: Caio2004$

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080